services:
  rails:
    image: bitsplease-project6
    build: 
      context: .
    volumes:
      - .:/code
    tty: true
    stdin_open: true
  db:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project6
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    
