services:
  rails:
    image: bitsplease-project6
    build: 
      context: .
    environment:
      - POSTGRES_PASSWORD=bitsplease
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    networks:
      bridge:
        ipv4_address: 172.20.0.2
  db:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=bitsplease
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project6
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      bridge:
        ipv4_address: 172.20.0.3
    
networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
