default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD")%>
  host: 172.20.0.3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>